title: F de Física
description: Hola
remote_theme: just-the-docs/just-the-docs@v0.6.2
color_scheme: foo
baseurl: "/F-de-Fisica"
url: "https://ferabyss.github.io/Ferabyss/"

logo: "/assets/images/logo3.png"
favicon_ico: "/assets/images/icon1.png"

math: katex


  
callouts:
  nota:
    title: Nota
    color: purple

defaults:
  -
    scope:
      path: "docs" # an empty string here means all files in the project
    values:
      layout: "default"
